//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Igman.DB.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticlesLike
    {
        public int ArticleID { get; set; }
        public int UserID { get; set; }
        public Nullable<System.DateTime> DateLike { get; set; }
        public string CreatorIP { get; set; }
        public Nullable<System.Guid> GUID { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual User User { get; set; }
    }
}
