//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Igman.DB.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public Article()
        {
            this.ArticlesLikes = new HashSet<ArticlesLike>();
            this.ArticlesRatings = new HashSet<ArticlesRating>();
            this.Comments = new HashSet<Comment>();
            this.Categories = new HashSet<Category>();
            this.Tags = new HashSet<Tag>();
        }
    
        public int ArticlesID { get; set; }
        public string Name { get; set; }
        public string Summary { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> DatePublish { get; set; }
        public Nullable<bool> IsPublish { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> Views { get; set; }
        public Nullable<System.Guid> GUID { get; set; }
        public string CreatorIP { get; set; }
        public string ModiferIP { get; set; }
        public string CreatorUserAgent { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<ArticlesLike> ArticlesLikes { get; set; }
        public virtual ICollection<ArticlesRating> ArticlesRatings { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Category> Categories { get; set; }
        public virtual ICollection<Tag> Tags { get; set; }
    }
}
