//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Igman.DB.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentID { get; set; }
        public Nullable<System.Guid> GUID { get; set; }
        public string CreatorIP { get; set; }
        public string CreatorUserAgent { get; set; }
        public string CreatorEmail { get; set; }
        public string CreatorName { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsSpam { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<int> CreatedByUserID { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<int> ModifiedByUserID { get; set; }
        public Nullable<int> ArticleID { get; set; }
        public Nullable<int> AnswerID { get; set; }
    
        public virtual Answer Answer { get; set; }
        public virtual Article Article { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
