//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Igman.DB.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Answers = new HashSet<Answer>();
            this.Articles = new HashSet<Article>();
            this.ArticlesLikes = new HashSet<ArticlesLike>();
            this.ArticlesRatings = new HashSet<ArticlesRating>();
            this.Comments = new HashSet<Comment>();
            this.Comments1 = new HashSet<Comment>();
            this.Questions = new HashSet<Question>();
            this.Roles = new HashSet<Role>();
        }
    
        public int UserID { get; set; }
        public Nullable<System.Guid> GUID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public Nullable<int> CityID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> PasswordFormat { get; set; }
        public string PasswordSalt { get; set; }
        public string Email { get; set; }
        public string LoweredEmail { get; set; }
        public string PasswordQuestion { get; set; }
        public string PasswordAnswer { get; set; }
        public string PhotoLocation { get; set; }
        public Nullable<System.DateTime> LastActivity { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public Nullable<System.DateTime> LastPasswordChange { get; set; }
        public Nullable<System.DateTime> LastLockout { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> IsLockedOut { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string Description { get; set; }
        public string LocationCover { get; set; }
        public string CoverPostion { get; set; }
        public Nullable<bool> IsFirst { get; set; }
    
        public virtual ICollection<Answer> Answers { get; set; }
        public virtual ICollection<Article> Articles { get; set; }
        public virtual ICollection<ArticlesLike> ArticlesLikes { get; set; }
        public virtual ICollection<ArticlesRating> ArticlesRatings { get; set; }
        public virtual City City { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Comment> Comments1 { get; set; }
        public virtual ICollection<Question> Questions { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
    }
}
